micronaut:
  application:
    name: guestoService
  server:
    port: 8080
  router:
    static-resources:
      rapidoc:
        paths: 'classpath:META-INF/rapidoc'
        mapping: '/rapidoc/**'
      swaggerSpec:
        paths: 'classpath:META-INF/swagger'
        mapping: '/swagger/**'
  endpoints:
    all:
      enabled: true
    health:
      enabled: true
      sensitive: false
  security:
    enabled: true
    intercept-url-map:
      - pattern: '/rapidoc/**'
        http-method: GET
        access:
          - isAnonymous()
      - pattern: '/swagger/**'
        http-method: GET
        access:
          - isAnonymous()

datasources:
  default:
    url: jdbc:postgresql://guesto.postgres.database.azure.com:5432/guesto
    username: postgres
    password: FH-Campus
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
