micronaut:
  application:
    name: guesto
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}

datasources:
  default:
    url: jdbc:postgresql://guesto.postgres.database.azure.com:5432/guesto
    username: postgres
    password: FH-Campus
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
