micronaut:
  application:
    name: guestoService
  server:
    port: 8080
    cors:
      enabled: true
  security:
    enabled: true
    intercept-url-map:
      - pattern: '/swagger-ui/**'
        http-method: GET
        access:
          - isAnonymous()
      - pattern: '/swagger/**'
        http-method: GET
        access:
          - isAnonymous()
  router:
    static-resources:
      swaggerui:
        paths: 'classpath:META-INF/swagger/views/swagger-ui'
        mapping: '/swagger-ui/**'
      swaggerSpec:
        paths: 'classpath:META-INF/swagger'
        mapping: '/swagger/**'
  endpoints:
    all:
      enabled: true
    health:
      enabled: true
      sensitive: false

datasources:
  default:
    url: jdbc:postgresql://guesto.postgres.database.azure.com:5432/guesto
    username: postgres
    password: FH-Campus
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
