openapi: 3.0.1
info:
  title: guesto
  version: "1.0"
paths:
  /event:
    get:
      operationId: listEvents
      responses:
        "200":
          description: listEvents 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      operationId: createEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventDTO'
        required: true
      responses:
        "200":
          description: createEvent 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
  /event/{id}:
    put:
      operationId: updateEvent
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventDTO'
        required: true
      responses:
        "200":
          description: updateEvent 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventDTO'
    delete:
      operationId: deleteEvent
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteEvent 200 response
          content:
            application/json:
              schema:
                type: object
  /event/{id}/checkin:
    put:
      operationId: checkInGuest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: checkInGuest 200 response
          content:
            application/json:
              schema:
                type: object
  /user:
    get:
      operationId: index
      responses:
        "200":
          description: index 200 response
          content:
            text/plain:
              schema:
                type: string
  /user/login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDTO'
        required: true
      responses:
        "200":
          description: login 200 response
          content:
            application/json:
              schema:
                type: object
  /user/register:
    post:
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDTO'
        required: true
      responses:
        "200":
          description: register 200 response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        eventName:
          type: string
        eventTime:
          type: string
          format: date-time
        maxGuestList:
          type: integer
          format: int32
        price:
          type: integer
        location:
          type: string
        createdBy:
          type: string
        createdTime:
          type: string
          format: date-time
        checkedInGuestsCount:
          type: integer
          format: int32
        guestList:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/GuestList'
    EventDTO:
      type: object
      properties:
        eventName:
          type: string
        eventTime:
          type: string
          format: date-time
        maxGuestList:
          type: integer
          format: int32
        price:
          type: integer
        location:
          type: string
        guestList:
          $ref: '#/components/schemas/GuestListDTO'
    Guest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        firstName:
          type: string
        lastName:
          type: string
        checkedIn:
          type: boolean
        guestList:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/GuestList'
    GuestDTO:
      required:
      - additionalGuests
      - firstName
      - id
      - lastName
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        checkedIn:
          type: boolean
        additionalGuests:
          type: integer
          format: int32
    GuestList:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        event:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Event'
        guests:
          type: array
          items:
            $ref: '#/components/schemas/Guest'
    GuestListDTO:
      required:
      - eventId
      - guests
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        eventId:
          type: integer
          format: int64
        guests:
          type: array
          items:
            $ref: '#/components/schemas/GuestDTO'
    LoginDTO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    RegisterDTO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
