name: Deploy Vue.js App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies and build Vue.js App
        run: |
          cd ./src/main/webapp/gusto-app
          npm install
          npm run build

      - name: Copy PDF file to build directory
        run: cp ./src/main/webapp/gusto-app/public/files/Benutzerdokumentation.pdf ./src/main/webapp/gusto-app/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./src/main/webapp/gusto-app/dist
