name: Deploy Vue.js App

on:
  push:
    branches:
      - main

jobs:
  deploy_vue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Debug GitHub Token
        run: echo ${{ secrets.TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Show current directory
        run: pwd

      - name: Install dependencies and build Vue.js App
        run: |
          cd $GITHUB_WORKSPACE/src/main/webapp/gusto-app
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist 
