name: Deploy Vue.js App

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  deploy_vue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Change directory to Vue.js app
        run: cd /src/main/webapp/gusto-app

      - name: Install Vue.js dependencies
        run: npm install

      - name: Build Vue.js App
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./dist
